version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=mongodb://mongo:27017/mydatabase
      - JWT_SECRET_KEY=ankitafgcdyyudghvdqgftyfqiuhioqiqpskxlknacjyasydghgdyuwguycg
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
