version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=mySuperSecretJWTKeyForAuthService
      - AUTH_SERVICE_SECRET=superSecretAuthServiceKey
  blog-service:
    build: ./blog-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogdb
      - JWT_SECRET=mySuperSecretJWTKeyForAuthService
      - AUTH_SERVICE_URL=http://auth-service:5000  
      - AUTH_SERVICE_SECRET=superSecretAuthServiceKey

  notification-service:
    build: ./notification-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notificationdb
      - JWT_SECRET=mySuperSecretJWTKeyForNotificationService
      - AUTH_SERVICE_SECRET=superSecretAuthServiceKey

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
