version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=your_jwt_secret

  blog-service:
    build: ./blog-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogdb
      - JWT_SECRET=your_jwt_secret

  notification-service:
    build: ./notification-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notificationdb
      - JWT_SECRET=your_jwt_secret

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
